"""phase4_add_feedback_and_user_disabled

Revision ID: 8edc35502aac
Revises: d4a2bd87fe5e
Create Date: 2026-04-27 12:59:27.951269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edc35502aac'
down_revision: Union[str, None] = 'd4a2bd87fe5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('error_index', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.Enum('fact_error', 'score_unfair', 'other'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_interview_id'), 'feedbacks', ['interview_id'], unique=False)
    op.add_column('users', sa.Column('is_disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_disabled')
    op.drop_index(op.f('ix_feedbacks_interview_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
