"""Interview orchestrator - resume-driven, stage-aware interview state machine.

Each stage has distinct behavior (see interviewer_agent.STAGE_CONFIG):
  初筛: verify basic skills, 2-3 Q, lenient
  HR面: STAR behavioral, 2-3 Q, must follow up on details
  技术面: deep-dive tech stack, 1-2 topics, mandatory 3-4 layer drill-down
  终面: open-ended, tech vision, 1-2 Q

Questions are generated dynamically by LLM based on resume skills/projects.
Question bank is no longer used during live interviews.
"""

import asyncio
import json
import logging
from datetime import datetime, timezone
from enum import Enum

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.agents.code_review_agent import CodeReviewAgent
from app.agents.interviewer_agent import InterviewerAgent, STAGE_CONFIG
from app.models.interview import Interview
from app.models.report import Report
from app.models.resume import Resume
from app.services.rag_service import RAGService
from app.services.scoring_service import ScoringService
from app.core.logging_config import truncate

logger = logging.getLogger(__name__)

FULL_STAGES = ["初筛", "HR面", "技术面", "终面"]


class OrchestratorState(Enum):
    WAITING_FOR_ANSWER = "waiting_for_answer"
    WAITING_FOR_CODE = "waiting_for_code"
    ENDED = "ended"


def _extract_top_skills(parsed_data: dict | None, limit: int = 3) -> list[str]:
    """Extract the strongest skills from resume parsed data."""
    if not parsed_data:
        return []
    skills = parsed_data.get("skills", [])
    if isinstance(skills, list):
        return skills[:limit] if len(skills) > limit else skills
    return []


def _extract_projects(parsed_data: dict | None) -> list[dict]:
    """Extract project experience from resume parsed data."""
    if not parsed_data:
        return []
    projects = parsed_data.get("project_experience", [])
    if isinstance(projects, list):
        return projects
    return []


class InterviewOrchestrator:
    """Resume-driven, stage-aware interview session manager.

    Questions are dynamically generated by LLM based on resume skills.
    Each stage has distinct personality via interviewer_agent.STAGE_CONFIG.
    """

    def __init__(
        self,
        interview: Interview,
        resume: Resume,
        db: AsyncSession,
    ):
        self.interview = interview
        self.resume = resume
        self.db = db
        self.interviewer = InterviewerAgent()
        self.code_reviewer = CodeReviewAgent()
        self.scoring_service = ScoringService(db)
        self.rag_service = RAGService(db)

        # Resume analysis
        self.top_skills = _extract_top_skills(self.resume.parsed_data if self.resume else {})
        self.projects = _extract_projects(self.resume.parsed_data if self.resume else {})

        # State
        self.state = OrchestratorState.WAITING_FOR_ANSWER
        self.stages: list[str] = FULL_STAGES
        if interview.selected_stages:
            self.stages = interview.selected_stages
        self.current_stage_idx = 0
        self.questions_in_stage = 0
        self.follow_up_count = 0  # per-question follow-up counter
        self.current_question: dict | None = None
        self.conversation: list[dict] = []
        self.stage_summaries: list[dict] = []
        self.pending_coding_question: dict | None = None

    def _add_pending_question(self):
        """Save current_question to conversation so reconnection can restore it."""
        if self.current_question:
            self.conversation.append({
                "question_text": self.current_question.get("text", ""),
                "user_answer_text": "",
                "stage": self.current_stage(),
                "score": 0,
                "dimensions_scores": {},
                "pending_question": True,
            })

    def _remove_pending_questions(self):
        """Remove unanswered pending entries before adding a scored answer."""
        self.conversation = [e for e in self.conversation if not e.get("pending_question")]

    # ===== Public API =====

    async def start(self) -> dict:
        """Start the interview, return the first message to send."""
        self.interview.status = "in_progress"
        self.interview.started_at = datetime.now(timezone.utc)
        self.interview.current_stage = self.stages[0]
        await self.db.commit()

        logger.info(
            f"面试开始: interview_id={self.interview.id}, stages={self.stages}"
        )

        return {
            "type": "session/started",
            "data": {
                "interview_id": self.interview.id,
                "stage": self.interview.current_stage,
                "message": f"欢迎参加{self.interview.position}的模拟面试，共{len(self.stages)}个阶段，现在开始吧！",
                "remaining_seconds": settings.INTERVIEW_MAX_DURATION,
            },
        }

    async def begin_current_stage(self) -> dict:
        """Send stage change and first question for current stage."""
        stage = self.current_stage()
        if not stage:
            return await self._end_with_message()

        self.interview.current_stage = stage
        self.questions_in_stage = 0
        await self.db.commit()

        # Transition message
        prev = self.stages[self.current_stage_idx - 1] if self.current_stage_idx > 0 else ""

        # Get first question for this stage
        first_msg = await self._generate_first_question(stage)
        question_text = first_msg.get("question_text") or ""

        return {
            "type": "control/stage_change",
            "data": {
                "from": prev,
                "to": stage,
                "message": f"进入【{stage}】环节",
                "question": question_text,
            },
        }

    async def handle_text(self, text: str) -> dict | None:
        """Process a text answer from the user."""
        if self.state != OrchestratorState.WAITING_FOR_ANSWER:
            logger.warning(f"收到文本输入但状态不匹配: state={self.state}")
            return None

        if not self.current_question:
            return await self._next_stage_message()

        self.questions_in_stage += 1

        question_text = self.current_question.get("text") or ""
        question_id = self.current_question.get("id")
        scoring_points_raw = self.current_question.get("scoring_points") or ""

        scoring_points = None
        if scoring_points_raw:
            try:
                scoring_points = json.loads(scoring_points_raw) if isinstance(scoring_points_raw, str) else scoring_points_raw
            except (json.JSONDecodeError, TypeError):
                pass

        # Real-time scoring
        score_result = await self.scoring_service.score_answer(
            question_text=question_text,
            user_answer=text,
            scoring_points=scoring_points,
            stage=self.current_stage(),
            position=self.interview.position,
            difficulty=self.interview.difficulty,
        )

        # Build structured answer record
        self._remove_pending_questions()
        answer_record = ScoringService.build_answer_record(
            question_id=question_id,
            question_text=question_text,
            user_answer=text,
            stage=self.current_stage(),
            score_result=score_result,
        )
        self.conversation.append(answer_record)

        logger.info(
            f"实时评分完成: interview_id={self.interview.id}, "
            f"stage={self.current_stage()}, score={score_result.get('total_score')}"
        )

        # Evaluate answer with stage-specific max questions + follow_up limit
        stage_cfg = STAGE_CONFIG.get(self.current_stage(), STAGE_CONFIG["初筛"])
        max_q = stage_cfg["max_questions"]
        evaluation = await self.interviewer.evaluate_answer(
            stage=self.current_stage(),
            position=self.interview.position,
            difficulty=self.interview.difficulty,
            question_text=question_text,
            user_answer=text,
            question_count=self.questions_in_stage,
            max_questions=max_q,
            follow_up_count=self.follow_up_count,
        )

        action = evaluation.get("action", "ask_question")
        logger.info(
            f"面试决策: interview_id={self.interview.id}, action={action}, "
            f"stage={self.current_stage()}, q_in_stage={self.questions_in_stage}"
        )

        if action == "follow_up":
            self.follow_up_count += 1
            # Enforce max_follow_ups — if exceeded, force move on
            if self.follow_up_count > stage_cfg["max_follow_ups"]:
                logger.info(
                    f"追问次数超限: follow_up_count={self.follow_up_count}, "
                    f"max={stage_cfg['max_follow_ups']}, 强制进入下一题或结束阶段"
                )
                if self.questions_in_stage >= max_q:
                    summary = f"{self.current_stage()}阶段追问已达上限，阶段完成"
                    self.stage_summaries.append({"stage": self.current_stage(), "summary": summary})
                    return await self._next_stage_message()
                else:
                    # Force a new main question via LLM
                    msg = "感谢你的回答，我们换个方向。"
                    self.follow_up_count = 0  # reset for new question
                    return {
                        "type": "ai/text",
                        "data": {"text": msg, "is_final": True},
                    }
            follow_up = evaluation.get("message", "")
            logger.info(f"追问: reason={truncate(evaluation.get('follow_up_reason', ''))}")
            question_text = evaluation.get("question_text") or ""
            self.current_question = {
                "text": question_text or follow_up or "请再详细说明一下？",
                "is_follow_up": True,
            }
            self._add_pending_question()
            # Avoid duplicate: only prepend follow_up if question_text
            # is not already contained within it (LLM often embeds both)
            display_text = question_text or follow_up or "请再详细说明一下？"
            if follow_up and follow_up != question_text and follow_up not in question_text:
                display_text = f"{follow_up}\n\n{question_text}"
            return {
                "type": "ai/text",
                "data": {"text": display_text, "is_final": True},
            }

        elif action == "stage_complete":
            summary = evaluation.get("stage_summary", f"{self.current_stage()}阶段完成")
            logger.info(f"阶段完成: stage={self.current_stage()}, summary={truncate(summary)}")
            self.stage_summaries.append({
                "stage": self.current_stage(),
                "summary": summary,
            })
            return await self._next_stage_message()

        else:  # ask_question
            # Hard limit: if we've exceeded max questions, force stage end
            if self.questions_in_stage >= max_q:
                logger.info(
                    f"主问题数已达上限: questions_in_stage={self.questions_in_stage}, "
                    f"max={max_q}, 强制结束阶段"
                )
                summary = f"{self.current_stage()}阶段问题数已达上限，阶段完成"
                self.stage_summaries.append({"stage": self.current_stage(), "summary": summary})
                return await self._next_stage_message()

            next_q = evaluation.get("question_text") or ""
            if not next_q:
                return await self._next_stage_message()

            self.follow_up_count = 0  # reset for new main question
            self.current_question = {"text": next_q, "is_follow_up": False}
            self._add_pending_question()
            msg = evaluation.get("message", "")
            # Avoid duplicate: if message already contains the question, just show question
            display_text = next_q
            if msg and msg != next_q and next_q not in msg:
                display_text = f"{msg}\n\n{next_q}"
            return {
                "type": "ai/text",
                "data": {"text": display_text, "is_final": True},
            }

    async def handle_code(self, code: str, language: str = "python") -> dict:
        """Process a code submission. Only valid in 技术面 stage."""
        logger.info(
            f"代码提交: interview_id={self.interview.id}, language={language}, "
            f"code_len={len(code)}"
        )
        self.state = OrchestratorState.WAITING_FOR_ANSWER

        if not self.pending_coding_question:
            return {
                "type": "ai/text",
                "data": {"text": "代码已收到，但当前没有待评审的编程题。", "is_final": True},
            }

        q_id = self.pending_coding_question.get("id", "")

        try:
            review = await self.code_reviewer.review(
                code=code,
                language=language,
                question_title=self.pending_coding_question.get("title", ""),
                question_description=self.pending_coding_question.get("description", ""),
                difficulty=self.interview.difficulty,
            )
        except Exception as e:
            logger.error(f"代码评审失败: {e}", exc_info=True)
            return {
                "type": "ai/code_review_error",
                "data": {"question_id": q_id, "error": "评审超时，请重试"},
            }

        # Store in conversation
        self.conversation.append({
            "stage": self.current_stage(),
            "type": "coding_challenge",
            "question": self.pending_coding_question,
            "submitted_code": code,
            "language": language,
            "review": review,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

        self.pending_coding_question = None

        return {
            "type": "ai/text",
            "data": {
                "text": self._format_code_review(review),
                "is_final": True,
            },
        }

    async def handle_end(self) -> dict:
        """User requests early end. Send end message; report generated in WS finally block."""
        self.state = OrchestratorState.ENDED
        self.interview.status = "completed"
        self.interview.ended_at = datetime.now(timezone.utc)
        await self.db.commit()

        return await self._build_end_message("completed")

    async def finalize(self) -> dict:
        """Normal completion - send end message; report generated in WS finally block."""
        self.state = OrchestratorState.ENDED
        self.interview.status = "completed"
        self.interview.ended_at = datetime.now(timezone.utc)
        await self.db.commit()

        return await self._build_end_message("completed")

    # ===== Helpers =====

    async def check_timeout(self) -> dict | None:
        """Check if interview has exceeded max duration. Returns end message or warning."""
        if not self.interview.started_at:
            return None
        started = self.interview.started_at.replace(tzinfo=timezone.utc)
        elapsed = (datetime.now(timezone.utc) - started).total_seconds()
        if elapsed > settings.INTERVIEW_MAX_DURATION:
            logger.warning(f"面试超时: interview_id={self.interview.id}, elapsed={elapsed}s")
            self.state = OrchestratorState.ENDED
            self.interview.status = "completed"
            self.interview.ended_at = datetime.now(timezone.utc)
            await self.db.commit()
            return await self._build_end_message("completed")
        # 3-minute warning
        remaining = settings.INTERVIEW_MAX_DURATION - elapsed
        if 0 < remaining <= 180 and not getattr(self, '_timeout_warned', False):
            self._timeout_warned = True
            return {
                "type": "ai/text",
                "data": {
                    "text": f"⏰ 面试时间还剩 {int(remaining // 60)} 分钟，当前问题回答完后将自动结束。",
                    "is_final": True,
                },
            }
        return None

    async def _generate_report_bg(self, interview_id: int):
        """Generate report in background with its own DB session.

        Must not share self.db — the main WebSocket handler may close its session
        before this task completes, causing a connection race.
        """
        try:
            from app.core.database import SessionLocal
            from app.services.report_generator import ReportGenerator

            async with SessionLocal() as bg_db:
                generator = ReportGenerator(bg_db)
                await generator.generate(interview_id)
        except Exception as e:
            logger.error(f"后台报告生成失败: interview_id={interview_id}, error={e}", exc_info=True)

    def current_stage(self) -> str:
        if self.current_stage_idx < len(self.stages):
            return self.stages[self.current_stage_idx]
        return ""

    async def _generate_first_question(self, stage: str) -> dict:
        """Generate the first question — LLM with question bank as few-shot reference."""
        self.follow_up_count = 0  # reset for new stage/question
        # Search question bank for relevant examples based on resume skills
        examples = await self.rag_service.search_examples(
            stage=stage,
            skills=self.top_skills,
            position=self.interview.position,
            difficulty=self.interview.difficulty,
            limit=3,
        )
        logger.info(
            f"题库示例匹配: stage={stage}, skills={self.top_skills}, "
            f"examples_found={len(examples)}"
        )
        result = await self.interviewer.start_stage(
            stage=stage,
            position=self.interview.position,
            difficulty=self.interview.difficulty,
            top_skills=self.top_skills,
            projects=self.projects,
            examples=examples,
        )
        question_text = result.get("question_text") or ""
        if question_text:
            self.current_question = {
                "text": question_text,
                "is_follow_up": False,
                "scoring_points": None,
            }
            self._add_pending_question()
        return result

    async def _next_stage_message(self) -> dict:
        """Advance to next stage or end interview."""
        self.current_stage_idx += 1
        if self.current_stage_idx >= len(self.stages):
            logger.info(f"所有阶段完成，即将结束: interview_id={self.interview.id}")
            return await self.finalize()

        logger.info(
            f"阶段切换: interview_id={self.interview.id}, to={self.current_stage()}, "
            f"index={self.current_stage_idx + 1}/{len(self.stages)}"
        )
        return await self.begin_current_stage()

    async def _end_with_message(self) -> dict:
        """All stages completed."""
        return await self.finalize()

    async def _build_end_message(self, reason: str) -> dict:
        """Build the session/end message."""
        # Generate a closing statement
        closing = await self.interviewer.generate_final_summary(
            position=self.interview.position,
            stage_summaries=self.stage_summaries,
        )

        return {
            "type": "session/end",
            "data": {
                "reason": reason,
                "message": closing,
            },
        }

    def _format_code_review(self, review: dict) -> str:
        """Format code review result as a readable text message."""
        total = review.get("total_score", 0)
        overall = review.get("overall_assessment", "")
        strengths = "\n".join(f"  ✓ {s}" for s in review.get("strengths", []))
        weaknesses = "\n".join(f"  ✗ {w}" for w in review.get("weaknesses", []))
        suggestions = "\n".join(f"  → {s}" for s in review.get("suggestions", []))

        return (
            f"代码评审完成（总分：{total}/100）\n\n"
            f"{overall}\n\n"
            f"✅ 优点：\n{strengths}\n\n"
            f"⚠️ 不足：\n{weaknesses}\n\n"
            f"💡 改进建议：\n{suggestions}"
        )


async def build_orchestrator(
    interview_id: int,
    db: AsyncSession,
) -> InterviewOrchestrator:
    """Factory: load interview and resume from DB, return orchestrator."""
    from app.models.resume import Resume

    result = await db.execute(
        select(Interview).where(Interview.id == interview_id)
    )
    interview = result.scalar_one_or_none()
    if not interview:
        raise ValueError(f"Interview {interview_id} not found")

    result = await db.execute(
        select(Resume).where(Resume.id == interview.resume_id)
    )
    resume = result.scalar_one_or_none()
    if not resume:
        raise ValueError(f"Resume {interview.resume_id} not found")

    return InterviewOrchestrator(interview=interview, resume=resume, db=db)
